Repository dbsystel/gitlab-ci-python-library, pull requests merged in 2021-03, with the labels that each got.

#13 Bug, Feature and Pull request templates:
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature.md
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: documentation

#18 fixed signature of gcip.addons.python.twine_upload made 'twine_reposi…
  gcip/addons/python/jobs.py
Labels: bug

#20 Added config.yml to force using issue templates.
  .github/ISSUE_TEMPLATE/config.yml
  CHANGELOG.md
Labels: bug

#21 Add GitHub config
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#22 Added new fixture to allow patching of os environment variable.
  .gitignore
  CHANGELOG.md
  tests/conftest.py
  tests/unit/comparison_files/test_readme_cache_jobs_test.yml
  tests/unit/test_cache.py
  tests/unit/test_readme_cache_jobs.py
Labels: enhancement

#23 Change behavior of PredefinedVariables class.
  CHANGELOG.md
  gcip/core/variables.py
Labels: enhancement

#26 Fix test_full_featured_cache test, missing env var.
  tests/unit/test_cache.py
Labels: bug
